#!/bin/bash
echo
printf "      ___                       ___\n"
printf "     /\\__\\                     /\\  \\ \n"
printf "    /:/ _/_       ___         /::\\  \\ \n"
printf "   /:/ /\\__\\     /\\__\\       /:/\\:\\  \\ \n"
printf "  /:/ /:/  /    /:/__/      /:/  \\:\\  \\ \n"
printf " /:/_/:/  /    /::\\  \\     /:/__/ \\:\\__\\ \n"
printf " \\:\\/:/  /     \\/\\:\\  \\__  \\:\\  \\ /:/  /\n"
printf "  \\::/__/         \\:\\/\\__\\  \\:\\  /:/  /\n"
printf "   \\:\\  \\          \\::/  /   \\:\\/:/  /\n"
printf "    \\:\\__\\         /:/  /     \\::/  /\n"
printf "     \\/__/         \\/__/       \\/__/\n"
echo
echo "  FOUNDATION FOR INTERWALLET OPERABILITY "
echo
/bin/systemctl status fio-nodeos.service --no-pager -n0 |head -3 |grep -B3 running && {
    SEC=$(( $(tail -100 /var/log/fio/nodeos.log |grep latency |tail -1 | awk -F'latency: ' '{print $2}' |awk '{print $1}') / 1000 ));
    if [[ "$SEC" -gt 60 ]] ;
        then DATE=$(date --date=@$(( $(date +%s) - "$SEC" )))
        printf "\n\t*** WARNING: nodeos is $SEC seconds behind ($DATE) ***\n";
    fi
    echo;
}

/bin/systemctl status fio-keosd.service --no-pager -n0 |head -3 |grep -B3 running && echo

exit 0

